### ISSUE TITLE
Montar estrutura básica de um API Rest usando express

### ISSUE THREAD

**Issue by rsdevigo** [monicacomcircunflexo/IFVV#2]

**Comment by ghost** [comment]
## Composição de uma estrutura básica de um API Rest usando **(REVISAR)**

![Capturar](https://user-images.githubusercontent.com/40694291/54453721-439de600-472e-11e9-9cc4-68486685e184.PNG)

**Comment by ghost** [comment]
## Tarefa 1 **(REVISAR)**

- Configuração do servidor.

 
### Server.js 

![server](https://user-images.githubusercontent.com/40694291/54459029-ddb85b00-473b-11e9-83ba-889277f2c29b.PNG)

### App.js

![app](https://user-images.githubusercontent.com/40694291/54459045-e7da5980-473b-11e9-9e6a-cc2679af2f9f.PNG)

**Comment by ghost** [comment]
## Tarefa 2 **(REVISAR)**
 - Definir pacotes NPM que serão utilizado na estrutura.
 - Link para estudar sobre express-validator. 
   https://express-validator.github.io/docs/
 - Link sobre o nodemon.
   https://nodemon.io/
- Link do express.
  https://expressjs.com/pt-br/4x/api.html
- Link do Body-parser.
  https://www.npmjs.com/package/body-parser
- Link do Consign.
  https://www.npmjs.com/package/consign

**Comment by phpmelhorjavascript** [comment]
## Tarefa 3

- Criar a classe Modelo(definir nome para classe).

**Comment by ytubeth3luz** [comment]
## Tarefa 4
- Configurar Firebase

**Comment by ytubeth3luz** [comment]
## Tarefa 5
- Configurar as rotas da API

**Comment by ytubeth3luz** [comment]
## Tarefa 6 **(REVISAR)**
- Configuração  package.json
![config](https://user-images.githubusercontent.com/40694291/54459213-5b7c6680-473c-11e9-9029-46b08b8df8bb.PNG)

- https://docs.npmjs.com/creating-a-package-json-file
