### ISSUE TITLE
Construir modelo de base de dados de usuários usando Firebase

### ISSUE THREAD

**Issue by rsdevigo** [monicacomcircunflexo/IFVV#3]

**Comment by rsdevigo** [comment]
Usará login de facebook ou google ?

**Comment by ghost** [comment]
Google  ganhou na votação da sala.

**Comment by ghost** [comment]
Estrutura cadastro de usuário no firebase

![image](https://user-images.githubusercontent.com/40694291/54873236-a7688480-4da8-11e9-82cb-a0bbae0f8ef7.png)

**Comment by ghost** [comment]
Criei a estrutura, baseado no print de tela enviado pela equipe da implementação mobile.
